package com.security.bull.signserver.adminsig.service.v1_3_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-09-23T11:30:19.510Z
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/", name = "adminSig")
@XmlSeeAlso({com.security.bull.signserver.adminsig.v1_3.ObjectFactory.class, com.bull.metasign.xmlsignaturepolicy.v3.TransformsType.class, com.bull.metasign.xmlsignaturepolicy.v3.ObjectFactory.class, com.security.bull.netutils.ObjectFactory.class, com.security.bull.signserver.sigservices.v1_3.ObjectFactory.class, com.security.bull.server.coreservices.v1_3.ObjectFactory.class, com.security.bull.server.coreservices.v1_3.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdminSig {

    /**
     * Deposit an X509Certificate for an existing Signature key
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/depositCertificateForSignatureKey")
    @WebResult(name = "depositCertForSkcResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "dCert4SkcResponse")
    public com.security.bull.server.coreservices.v1_3.WSResponse depositCertificateForSignatureKey(
        @WebParam(partName = "dCert4Skc", name = "depositCertForSkc", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDepositCertificateForSignatureKey dCert4Skc
    );

    /**
     * Create a signature key (public/private key association) for the requiring signer using the specified HSM generated key pair ckaid. Upon successful completion, the signature key will be created on the server (it's id is returned in the response) pointing to the specified Key pair in the HSM.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/createSignatureKeyFromExistingKeyPair")
    @WebResult(name = "createSkcResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "cSkcFKPResponse")
    public com.security.bull.signserver.adminsig.v1_3.CreateSignatureKeyCertResponse createSignatureKeyFromExistingKeyPair(
        @WebParam(partName = "cSkcFKP", name = "createSkcFKP", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSCreateSignatureKeyCertFromKeyPair cSkcFKP
    );

    /**
     * Retrieves an existing signature policy from the server.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/retrieveSignaturePolicy")
    @WebResult(name = "retrieveSigPolResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "rSigPolR")
    public com.security.bull.signserver.adminsig.v1_3.RetrieveSignaturePolicyResponse retrieveSignaturePolicy(
        @WebParam(partName = "rSigPol", name = "retrieveSigPol", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSRetrieveSignaturePolicy rSigPol
    );

    /**
     * Update an existing signature Profile with new value.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/updateSignatureProfile")
    @WebResult(name = "artifactIdResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "updatedId")
    public com.security.bull.server.coreservices.v1_3.ArtifactIdResponse updateSignatureProfile(
        @WebParam(partName = "uSigProfile", name = "updateSigProfile", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSUpdateSigProf uSigProfile
    );

    /**
     * A Key and Certificate association (PKCS#12 or other keystore format) is deposited on the server for future usage. The key-certificate association can not be verified by the server upon deposit (the store's password is not transmitted in the request for security reasons). The validity of the deposit is verified when it is activated (in an other WSOperation). For example, signserver signers can deposit signature key and associated certificate through this operation and then invoke a signature dedicated WSOperation to use the deposit and create a signature key from it. This second operation will include a parameter corresponding to the transport password used to protect the deposit, it is only then that the server will be able to read the store's content.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/depositKeystore")
    @WebResult(name = "depositKeystoreResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "dKeystoreR")
    public com.security.bull.signserver.adminsig.v1_3.DepositKeystoreResponse depositKeystore(
        @WebParam(partName = "dKekstore", name = "depositKeystore", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDepositKeystore dKekstore
    );

    /**
     * Retrieves an existing signature profile from the server.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/retrieveSignatureProfile")
    @WebResult(name = "retrieveSigProfResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "rSigProfR")
    public com.security.bull.signserver.adminsig.v1_3.RetrieveSignatureProfileResponse retrieveSignatureProfile(
        @WebParam(partName = "rSigProf", name = "retrieveSigProf", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSRetrieveSignatureProfile rSigProf
    );

    /**
     * Generate a Signature Key (public/private key association) for the specified key-pair generation profile. The signature key's private key will be securely stored on the server's HSM.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/createSignatureKeyFromProfile")
    @WebResult(name = "createSkcResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "cSkcFProfileResponse")
    public com.security.bull.signserver.adminsig.v1_3.CreateSignatureKeyCertResponse createSignatureKeyFromProfile(
        @WebParam(partName = "cSkcFProfile", name = "createSkcFProfile", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSCreateSignatureKeyCertFromProfile cSkcFProfile
    );

    /**
     * Deletes the signature key of the specified signature key Id.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/deleteSignatureKey")
    @WebResult(name = "deleteSigKeyResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "delSigKeyR")
    public com.security.bull.signserver.adminsig.v1_3.DeleteSignatureKeyResponse deleteSignatureKey(
        @WebParam(partName = "delSigKey", name = "deleteSigKey", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDeleteSignatureKey delSigKey
    );

    /**
     * Deposit a signature Profile for further use by signers on the server.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/depositSignatureProfile")
    @WebResult(name = "artifactIdResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "dSigProfR")
    public com.security.bull.server.coreservices.v1_3.ArtifactIdResponse depositSignatureProfile(
        @WebParam(partName = "dSigProf", name = "depositSigProfile", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDepositSignatureProfile dSigProf
    );

    /**
     * Create a signature key (public/private key and signing certificate association) for the requiring signer using the specified previously deposited PKCS#12. Upon successful completion, the signature key will be created on the server (it's id is returned in the response) and the specified PKCS#12 deleted from theserver.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/createSignatureKeyFromPkcs12")
    @WebResult(name = "createSkcResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "cSkcFP12Response")
    public com.security.bull.signserver.adminsig.v1_3.CreateSignatureKeyCertResponse createSignatureKeyFromPkcs12(
        @WebParam(partName = "cSkcFP12", name = "createSkcFPkcs12", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSCreateSignatureKeyCertFromPkcs12 cSkcFP12
    );

    /**
     * Activates a signature Key for OTP operations
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/activateSignatureKey")
    @WebResult(name = "activateSignatureKeyResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "activateSignatureKeyResponse")
    public com.security.bull.signserver.adminsig.v1_3.ActivateSignatureKeyResponse activateSignatureKey(
        @WebParam(partName = "activSigK", name = "activateSignatureKey", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSActivateSignatureKey activSigK
    );

    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/listSignaturePolicies")
    @WebResult(name = "listSigPolsResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "lSigPoResponse")
    public com.security.bull.signserver.adminsig.v1_3.ListSigPolResponse listSignaturePolicies(
        @WebParam(partName = "lSigPols", name = "listSigPols", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSListSigPol lSigPols
    );

    /**
     * Generate a Certificate Signing Request for an existing Signature Key.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/generateCsrForSignatureKey")
    @WebResult(name = "csrForSkcResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "gCSR4SKCResponse")
    public com.security.bull.signserver.adminsig.v1_3.CsrForSignatureKeyResponse generateCsrForSignatureKey(
        @WebParam(partName = "gCsr4Skc", name = "generateCsrForSkc", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSGenerateCsrForSignatureKey gCsr4Skc
    );

    /**
     * Deletes the signature policy of specified OID.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/deleteSignaturePolicy")
    @WebResult(name = "deleteSigPolResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "delSigPolR")
    public com.security.bull.signserver.adminsig.v1_3.DeleteSignaturePolicyResponse deleteSignaturePolicy(
        @WebParam(partName = "delSigPol", name = "deleteSigPol", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDeleteSignaturePolicy delSigPol
    );

    /**
     * Deletes the signature profile of specified ServerId.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/deleteSignatureProfile")
    @WebResult(name = "deleteSigProfResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "delSigProfR")
    public com.security.bull.signserver.adminsig.v1_3.DeleteSignatureProfileResponse deleteSignatureProfile(
        @WebParam(partName = "delSigProf", name = "deleteSigProf", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDeleteSignatureProfile delSigProf
    );

    /**
     * Deletes the signature profile of specified ServerId.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/deleteSignatureKeyGenerationProfile")
    @WebResult(name = "deleteSKGProfResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "delSKGProfR")
    public com.security.bull.signserver.adminsig.v1_3.DeleteSigKeyGenProfileResponse deleteSignatureKeyGenerationProfile(
        @WebParam(partName = "delSKGProf", name = "deleteSKGProf", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDeleteSigKeyGenProfile delSKGProf
    );

    /**
     * Creation of a signature certificate for an existing signature key
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/requestCertificateForSignatureKey")
    @WebResult(name = "requestCertForSkcResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "rCert4SkcR")
    public com.security.bull.signserver.adminsig.v1_3.CertificateForSignatureKeyResponse requestCertificateForSignatureKey(
        @WebParam(partName = "rCert4Skc", name = "requestCertForSkc", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSRequestCertificateForSignatureKey rCert4Skc
    );

    /**
     * Deposit a signature key generation profile for further use when generating signature keys on the server.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/depositSignatureKeyGenerationProfile")
    @WebResult(name = "artifactIdResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "sigKeyGenProfileId")
    public com.security.bull.server.coreservices.v1_3.ArtifactIdResponse depositSignatureKeyGenerationProfile(
        @WebParam(partName = "dSKGProf", name = "sigKeyGenProfParams", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDepSigKeyGenProfile dSKGProf
    );

    /**
     * An update of a signature secret protecting signer's signature keys.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/updateSignatureSecret")
    @WebResult(name = "updateSignatureSecretResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "uSigSecretResponse")
    public com.security.bull.server.coreservices.v1_3.WSResponse updateSignatureSecret(
        @WebParam(partName = "uSigSecret", name = "updateSignatureSecret", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSUpdateSignatureSecret uSigSecret
    );

    /**
     * Deposit (or updates) a signature Policy for further use by signers on the server. 
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/depositSignaturePolicy")
    @WebResult(name = "artifactIdResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "dSigPolR")
    public com.security.bull.server.coreservices.v1_3.ArtifactIdResponse depositSignaturePolicy(
        @WebParam(partName = "dSigPol", name = "depositSigPolicy", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSDepositSignaturePolicy dSigPol
    );

    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/listSignatureProfile")
    @WebResult(name = "listSigProfileResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "lSigProfileResponse")
    public com.security.bull.signserver.adminsig.v1_3.ListSigProfileResponse listSignatureProfile(
        @WebParam(partName = "lSigProfile", name = "listSigProfile", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSListSigProfile lSigProfile
    );

    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/listSignatureKeyGenerationProfile")
    @WebResult(name = "listSKGPResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "lSKGPResponse")
    public com.security.bull.signserver.adminsig.v1_3.ListSKGPResponse listSignatureKeyGenerationProfile(
        @WebParam(partName = "lSKGP", name = "listSKGP", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSListSKGP lSKGP
    );

    /**
     * Retrieves an existing a signature key generation profile from the server.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/retrieveSignatureKeyGenerationProfile")
    @WebResult(name = "retrieveSkgProfResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "rSkgProfR")
    public com.security.bull.signserver.adminsig.v1_3.RetrieveSkgProfileResponse retrieveSignatureKeyGenerationProfile(
        @WebParam(partName = "rSkgProf", name = "retrieveSkgProf", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSRetrieveSkgProfile rSkgProf
    );

    /**
     * Modifies a signature key generation profile on the server.
     */
    @WebMethod(action = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/updateSignatureKeyGenerationProfile")
    @WebResult(name = "updateSkgProfileResponse", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/", partName = "uSkgProfR")
    public com.security.bull.server.coreservices.v1_3.WSResponse updateSignatureKeyGenerationProfile(
        @WebParam(partName = "uSkgProf", name = "updateSkgProfile", targetNamespace = "http://www.bull.security.com/SignServer/adminSig/v1.3.0/")
        com.security.bull.signserver.adminsig.v1_3.WSUpdateSkgProfile uSkgProf
    );
}
