package com.security.bull.signserver.adminsig.service.v1_3_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-09-23T11:30:19.610Z
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "adminSig", 
                  wsdlLocation = "file:/D:/MavenProject/clientsignature/clientsignature/src/main/resources/AdminSigSOAP/AdminSig.wsdl",
                  targetNamespace = "http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/") 
public class AdminSig_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/", "adminSig");
    public final static QName AdminSigSOAP = new QName("http://www.bull.security.com/SignServer/adminSig/service/v1.3.0/", "adminSigSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/MavenProject/clientsignature/clientsignature/src/main/resources/AdminSigSOAP/AdminSig.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdminSig_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/MavenProject/clientsignature/clientsignature/src/main/resources/AdminSigSOAP/AdminSig.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdminSig_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdminSig_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminSig_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminSig_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminSig_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminSig_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AdminSig
     */
    @WebEndpoint(name = "adminSigSOAP")
    public AdminSig getAdminSigSOAP() {
        return super.getPort(AdminSigSOAP, AdminSig.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminSig
     */
    @WebEndpoint(name = "adminSigSOAP")
    public AdminSig getAdminSigSOAP(WebServiceFeature... features) {
        return super.getPort(AdminSigSOAP, AdminSig.class, features);
    }

}
