package com.security.bull.server.admin.service.v1_3_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-09-19T15:11:09.068Z
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.bull.security.com/Server/admin/service/v1.3.0/", name = "Admin")
@XmlSeeAlso({com.security.bull.server.admin.v1_3.ObjectFactory.class, com.security.bull.signserver.extensions.v1_3.ObjectFactory.class, com.security.bull.server.coreservices.v1_3.ObjectFactory.class, com.security.bull.server.coreadmin.v1_3.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Admin {

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/deleteUser")
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "dUserR")
    public com.security.bull.server.admin.v1_3.DeleteResponse deleteUser(
        @WebParam(partName = "dUser", name = "deleteUser", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSDeleteUser dUser
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/listGroups")
    @WebResult(name = "listGroupsResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "listGroupsResponse")
    public com.security.bull.server.admin.v1_3.ListGroupsResponse listGroups(
        @WebParam(partName = "listGroups", name = "listGroups", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSListGroups listGroups
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/updateUser")
    @WebResult(name = "updateUserResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "uUserR")
    public com.security.bull.server.admin.v1_3.UpdateUserResponse updateUser(
        @WebParam(partName = "uUser", name = "updateUser", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSUpdateUser uUser
    );

    /**
     * Creates a new User.
     */
    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/createUser")
    @WebResult(name = "createUserResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "cUserR")
    public com.security.bull.server.admin.v1_3.CreateUserResponse createUser(
        @WebParam(partName = "cUser", name = "createUser", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSCreateUser cUser
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/deleteGroup")
    @WebResult(name = "deleteGroupResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "dGroupR")
    public com.security.bull.server.admin.v1_3.DeleteResponse deleteGroup(
        @WebParam(partName = "dGroup", name = "deleteGroup", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSDeleteGroup dGroup
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/removeUsersFromGroup")
    @WebResult(name = "removeUsersFromGroupResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "removeUFGR")
    public com.security.bull.server.admin.v1_3.UsersGroupResponse removeUsersFromGroup(
        @WebParam(partName = "removeUFG", name = "removeUsersFromGroup", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSRemoveUsersFromGroup removeUFG
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/listUsers")
    @WebResult(name = "listUsersResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "listUsersResponse")
    public com.security.bull.server.admin.v1_3.ListUsersResponse listUsers(
        @WebParam(partName = "listUsers", name = "listUsers", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSListUsers listUsers
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/addUsersToGroup")
    @WebResult(name = "addUsersToGroupResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "addU2GR")
    public com.security.bull.server.admin.v1_3.UsersGroupResponse addUsersToGroup(
        @WebParam(partName = "addU2G", name = "addUsersToGroup", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSAddUsersToGroup addU2G
    );

    /**
     * A Key and Certificate association (PKCS#12 or other keystore format) is deposited on the server for future usage. The key-certificate association can not be verified by the server upon deposit (the store's password is not transmitted in the request for security reasons). The validity of the deposit is verified when it is activated (in an other WSOperation). For example, signserver signers can deposit signature key and associated certificate through this operation and then invoke a signature dedicated WSOperation to use the deposit and create a signature key from it. This second operation will include a parameter corresponding to the transport password used to protect the deposit, it is only then that the server will be able to read the store's content.
     */
    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/depositKeystore")
    @WebResult(name = "depositKeystoreResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "dKeystoreR")
    public com.security.bull.server.admin.v1_3.DepositKeystoreResponse depositKeystore(
        @WebParam(partName = "dKekstore", name = "depositKeystore", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSDepositKeystore dKekstore
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/consultUser")
    @WebResult(name = "consultUserResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "consultUserResponse")
    public com.security.bull.server.admin.v1_3.ConsultUserResponse consultUser(
        @WebParam(partName = "consultUser", name = "consultUser", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSConsultUser consultUser
    );

    @WebMethod(action = "http://www.bull.security.com/Server/admin/service/v1.3.0/createGroup")
    @WebResult(name = "createGroupResponse", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/", partName = "cGroupR")
    public com.security.bull.server.admin.v1_3.CreateGroupResponse createGroup(
        @WebParam(partName = "cGroup", name = "createGroup", targetNamespace = "http://www.bull.security.com/Server/admin/v1.3.0/")
        com.security.bull.server.admin.v1_3.WSCreateGroup cGroup
    );
}
