package com.security.bull.server.admin.service.v1_3_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-09-19T15:11:09.162Z
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "Admin", 
                  wsdlLocation = "file:/D:/MavenProject/clientsignature/clientsignature/src/main/resources/Admin/Admin.wsdl",
                  targetNamespace = "http://www.bull.security.com/Server/admin/service/v1.3.0/") 
public class Admin_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.bull.security.com/Server/admin/service/v1.3.0/", "Admin");
    public final static QName AdminSOAP = new QName("http://www.bull.security.com/Server/admin/service/v1.3.0/", "AdminSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/MavenProject/clientsignature/clientsignature/src/main/resources/Admin/Admin.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Admin_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/MavenProject/clientsignature/clientsignature/src/main/resources/Admin/Admin.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Admin_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Admin_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Admin_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Admin_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Admin_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Admin_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminSOAP")
    public Admin getAdminSOAP() {
        return super.getPort(AdminSOAP, Admin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminSOAP")
    public Admin getAdminSOAP(WebServiceFeature... features) {
        return super.getPort(AdminSOAP, Admin.class, features);
    }

}
